### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by merolaika** [danivs10/Automatic-Video-Generator-for-youtube#2]
Hello again sir, I duplicated the sound fields from 0 to 10 (for i in range(5)) in CreateVideo.py Line: 21, I made the field 10 but it gave an error. Then I tested backwards from 10 but it only works in 3. Can we only translate 3 sounds? I would appreciate your feedback on the subject. I tried to do this to extend the video duration. Can you tell me if there is a different way?

**Comment by danivs10** [comment]
Heey @merolaika glad to have you back! Let me take a look into this. Theoretically it should not be a problem to translate more sounds but let me drill through the issue first.

**Comment by danivs10** [comment]
Okay @merolaika I have refactored the code. Now it should work okay. However, remember that you must have as many texts (in the text parameter array of the add_captions method) as audio clips you have inside the audio folder. Let me know if it works now and I am here for any other question.

**Comment by merolaika** [comment]
Hello again;

`C:\Automatic-Video-Generator-for-youtube>py main.py "cat facts"
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 285, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Automatic-Video-Generator-for-youtube\main.py", line 2, in <module>
    import CreateVideo
  File "C:\Automatic-Video-Generator-for-youtube\CreateVideo.py", line 39, in <module>
    add_captions(texts)
  File "C:\Automatic-Video-Generator-for-youtube\CreateVideo.py", line 25, in add_captions
    audio_clips.append(AudioFileClip(audioFileName))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\moviepy\audio\io\readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"
OSError: MoviePy error: failed to read the duration of file audio\1.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
audio\1: Permission denied`
